version: '3.5'

services:
  nginx:
    build: ./nginx/
    networks:
      - nginx

  apache:
    build: ./apache/
    networks:
      - apache


networks:
  nginx:
    name: nginx_network
#    driver: custom-driver-1

  apache:
    name: apache_network
#    driver: custom-driver-2
