version: '3.9'

services:
  nginx:
    image: localhost:5000/epam/nginx:v.0.1
    volumes:
      - './app:/var/www/html/'
#Добавил по заданию, но это будет работать только в swarm или docker stack
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - "8081:80"
    networks:
      - nginx

  apache:
    image: localhost:5000/epam/apache:v.0.1
    volumes:
      - './app:/var/www/html/'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - "8082:80"
    networks:
      - apache


networks:
  nginx:
    name: nginx_network

  apache:
    name: apache_network
